### ISSUE TITLE
Potential GPLv2 License Violation

### ISSUE THREAD

**Issue by jornmann** [RiiConnect24/Wii-Mod-Lite#8]
As the source code for Wii Mod Lite is not available, you might be violating GPLv2 since I suspect WML to contain source code from https://github.com/FIX94/Some-YAWMM-Mod, and therefore, https://github.com/waninkoko/wad-manager.

Since you are not the original creator of WML, please contact the original author about this issue.

**Comment by Artuto** [comment]
How exactly are we violating the license?

**Comment by jornmann** [comment]
GPLv2 requires the programs source to be disclosed and the license to be the same (GPLv2). WML is not licensed under GPLv2, and is proprietary. This is why it violates the license. https://choosealicense.com/licenses/gpl-2.0/

**Comment by Artuto** [comment]
Well we are not the original author nor have the source code or even the ability to relicense ¯\_(ツ)_/¯.

**Comment by jornmann** [comment]
Then, as I've said before, contact the original author.

**Comment by larsenv** [comment]
We've tried to get ahold of the original author (who is Chinese) to no avail. I even asked someone from China to help contact them on the forum that they visit (tvgzone), but they couldn't register because they couldn't get a confirmation email for their account.

I wanted the source code, but it's not my fault that they didn't share the source code.

**Comment by jornmann** [comment]
Well, that doesn't change the fact that you are still in violation of the GPLv2 license.

**Comment by Artuto** [comment]
There is nothing we can do, we cannot just magically generate the source code.
